// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz-wWkl1nHhpLGjWXHuyMEyPS3ixu_PWs',
    appId: '1:765122054961:web:ae4d4e637c65497f697e10',
    messagingSenderId: '765122054961',
    projectId: 'nodemcu5575',
    authDomain: 'nodemcu5575.firebaseapp.com',
    databaseURL:
        'https://nodemcu5575-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nodemcu5575.appspot.com',
    measurementId: 'G-7R1S188E4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF4AoGAriXnTm_mt6VLUsWDNcz9xDEdVs',
    appId: '1:765122054961:android:5aa3e26b4d1a38ab697e10',
    messagingSenderId: '765122054961',
    projectId: 'nodemcu5575',
    databaseURL:
        'https://nodemcu5575-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nodemcu5575.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMPoyERiiBhAPdM3p4yqp_KS6YPE18daM',
    appId: '1:765122054961:ios:2be893a34cd9f70c697e10',
    messagingSenderId: '765122054961',
    projectId: 'nodemcu5575',
    databaseURL:
        'https://nodemcu5575-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nodemcu5575.appspot.com',
    iosBundleId: 'com.aries.BBBSMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMPoyERiiBhAPdM3p4yqp_KS6YPE18daM',
    appId: '1:765122054961:ios:a655eaeef8bfc1ca697e10',
    messagingSenderId: '765122054961',
    projectId: 'nodemcu5575',
    databaseURL:
        'https://nodemcu5575-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nodemcu5575.appspot.com',
    iosBundleId: 'com.aries.BBBSMobile.RunnerTests',
  );
}
